// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPN3dTKFR8thkIKS9awX5riTbswVvmMsE',
    appId: '1:1039998036472:web:5c75449ab546ca03680e0d',
    messagingSenderId: '1039998036472',
    projectId: 'cashflow-e7d77',
    authDomain: 'cashflow-e7d77.firebaseapp.com',
    storageBucket: 'cashflow-e7d77.appspot.com',
    measurementId: 'G-K3VL4T74VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAqgc-7ifdyzqE3V5-vRRUYnteHOORdM',
    appId: '1:1039998036472:android:4a178e37aedba0ea680e0d',
    messagingSenderId: '1039998036472',
    projectId: 'cashflow-e7d77',
    storageBucket: 'cashflow-e7d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMCR7cjMOMblQX2EaodbJkcBHYMmyHtOo',
    appId: '1:1039998036472:ios:ce7f10b9a88b9442680e0d',
    messagingSenderId: '1039998036472',
    projectId: 'cashflow-e7d77',
    storageBucket: 'cashflow-e7d77.appspot.com',
    iosBundleId: 'com.example.cashflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMCR7cjMOMblQX2EaodbJkcBHYMmyHtOo',
    appId: '1:1039998036472:ios:ce7f10b9a88b9442680e0d',
    messagingSenderId: '1039998036472',
    projectId: 'cashflow-e7d77',
    storageBucket: 'cashflow-e7d77.appspot.com',
    iosBundleId: 'com.example.cashflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPN3dTKFR8thkIKS9awX5riTbswVvmMsE',
    appId: '1:1039998036472:web:f8d3db39c468602d680e0d',
    messagingSenderId: '1039998036472',
    projectId: 'cashflow-e7d77',
    authDomain: 'cashflow-e7d77.firebaseapp.com',
    storageBucket: 'cashflow-e7d77.appspot.com',
    measurementId: 'G-453M6VQTWE',
  );
}
